from decimal import Decimal
from typing import Callable
import re

text = "Загальний дохід працівника складається з декількох\
      частин: 1000.01 як основний дохід, доповнений \
        додатковими надходженнями 27.45 і 324.00 доларів."


def generator_numbers(text: str):
    # Finding all decimal numbers in the text that are separated by spaces
    decimal_list = re.findall(r' \d+.\d+ ', text)
    # Creating a generator to yield each decimal number
    for decimal in decimal_list:
        yield decimal

def sum_profit(text: str, func: Callable):
    total = Decimal(0)
    # Iterating over all decimal numbers generated by generator_numbers and summing them
    for decimal in generator_numbers(text):
        total += Decimal(decimal)
    return total

# Calculate total income by summing all identified decimal numbers in the text
total_income = sum_profit(text, generator_numbers)
print(f"Загальний дохід: {total_income}")
